apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: 296710535627.dkr.ecr.ap-south-1.amazonaws.com/grafana_repo
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
          env:
            - name: GF_DEFAULT_APP_MODE
              value: "development"
            - name: GF_USERS_DEFAULT_THEME
              value: "light"
            - name: GF_SERVER_DOMAIN
              value: "evahanam.dev.nichesolv.com"
            - name: GF_SERVER_ROOT_URL
              value: "https://evahanam.dev.nichesolv.com/grafana/"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_SECURITY_ALLOW_EMBEDDING
              value: "true"
            - name: GF_USERS_ALLOW_ORG_CREATE
              value: "true"
            #---------DB SETTINGS
            - name: GF_DATABASE_TYPE
              value: "postgres"
            - name: GF_DATABASE_HOST
              value: "10.0.2.229:5432"
            - name: GF_DATABASE_NAME
              value: "grafana"
            - name: GF_DATABASE_USER
              value: "devgrafanauser"
            - name: GF_DATABASE_PASSWORD
              value: "evGr@f@n@123!@#"
            #---------AUTH PROXY SETTINGS
            - name: GF_AUTH_LOGIN_COOKIE_NAME
              value: "grafana_session"
            - name: GF_AUTH_PROXY_ENABLED
              value: "true"
            - name: GF_AUTH_PROXY_HEADER_NAME
              value: "X-WEBAUTH-USER"
            - name: GF_AUTH_PROXY_HEADER_PROPERTY
              value: "email"
            - name: GF_AUTH_PROXY_AUTH_SIGN_UP
              value: "true"
            - name: GF_AUTH_PROXY_SYNC_TTL
              value: "60"
            - name: GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN
              value: "true"
            - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
              value: "/etc/grafana/provisioning/dashboards/Home.json"
            - name: GF_INSTALL_PLUGINS
              value: "grafana-worldmap-panel,natel-plotly-panel,volkovlabs-echarts-panel,michaeldmoore-multistat-panel,marcusolsson-static-datasource,marcusolsson-dynamictext-panel,orchestracities-map-panel"
            #-------OTHER ENV VARIABLES
            - name: DB_URL
              value: "10.0.2.229:5432"
            - name: DB_USER
              value: "grafanareader"
            - name: DB_PASSWORD
              value: "un3A51n355-5k4T3p4rk-5Cry3r-Sl1nk1n6"
            - name: POC_DB
              value: "pocdata"
            - name: POC_DS_UID
              value: "pocdata_uid"
            - name: EVAHANA_DB
              value: "evahana"
            - name: EVAHANA_DS_UID
              value: "evahana_uid"
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort