apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafanaproxy-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: grafanaproxy
  template:
    metadata:
      labels:
        app: grafanaproxy
    spec:
      containers:
        - name: grafanaproxy
          image: 296710535627.dkr.ecr.ap-south-1.amazonaws.com/grafana_proxy_repo:latest
          env:
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 4000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: grafanaproxy-service
spec:
  selector:
    app: grafanaproxy
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort